# 修改后相关步骤示例
- name: Download Rules
  if: steps.changes.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
  continue-on-error: true
  run: |
    python ./data/python/utils/dl.py
    
- name: Merge Rules
  if: steps.changes.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
  run: |
    python ./data/python/utils/merge.py
    
- name: Generate dns Rules
  if: steps.changes.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
  run: |
    python ./data/python/rules_generator/filter-dns.py

# 其他步骤类似更新路径...

- name: Update Title & ReadMe
  if: steps.changes.outputs.any_changed == 'true' || github.event_name == 'workflow_dispatch' || github.event_name == 'schedule'
  run: |
    python ./data/python/utils/title.py
    python ./data/python/utils/clean-readme.py