name: Update Rules

on:
  push:
    branches: [ "master" ]
    paths:
      - 'data/mod/**'
      - '.github/workflows/**'
  schedule:
    - cron: '0 16 * * *'  # 北京时间0点执行
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      SHOULD_RUN: ${{ github.event_name == 'workflow_dispatch' || github.event_name == 'schedule' || steps.changes.outputs.any_changed == 'true' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            any_changed:
              - 'data/mod/**'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pytz

      - name: Download Rules
        if: env.SHOULD_RUN
        run: |
          python ./data/python/dl.py

      - name: Merge Rules
        if: env.SHOULD_RUN
        run: |
          python ./data/python/merge.py

      - name: Generate filter Rules
        if: env.SHOULD_RUN
        run: |
          python ./data/python/filter-ad.py
   
      - name: Generate mihomo Rules
        if: env.SHOULD_RUN
        run: |
          python ./data/python/mihomo.py

      - name: Generate loon Rules
        if: env.SHOULD_RUN
        run: |
          python ./data/python/loon.py

      - name: Generate Domain List
        if: env.SHOULD_RUN
        run: |
          python ./data/python/domain_list.py

      - name: Update Title&ReadMe
        if: env.SHOULD_RUN
        run: |
          python ./data/python/title.py
          python ./data/python/clean-readme.py

      - name: Commit Changes
        if: env.SHOULD_RUN
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Updated at $(TZ=UTC-8 date +'%Y-%m-%d %H:%M:%S')（北京时间）"
          branch: master
          push_options: --force-with-lease

      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 3
          keep_minimum_runs: 5